=== dannyxu100/daCMS/sys_admin/module/seo2/kw.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="kall">
	<xs:complexType> 
		<xs:sequence>
			<xs:element name="kgroup" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="kdomain" type="xs:string"/>
						<xs:element name="kword" type="xs:string" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== dannyxu100/daCMS/sys_admin/module/seo2/kw.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
	文件出处：http://www.baiek.com/	交流邮件与QQ: 1468085800@qq.com
	关键字列表文件说明：
	本文件罗列了多个域名+关键字组，以及每一组的一个域名下对应多个关键字，用于批量查询关键字的百度排名。
	关键字列表使用XML格式文件，格式规则见kw.xsd文件。
	用户可以仿照KW.XML文件建立自己的关键字列表清单，文件名随意。
	每个kgroup组就是待查询的一组关键字以及所针对的域名。
	每个kgroup组内必须包含一个域名（kdomain项），也就是用户要查询这个域名下多个关键字在百度的排名，。
	每个kgroup组内必须包含一个或多个关键字（kword项）。
	依据上述规则，用户可建立多个kgroup组或者只保留一个，后者表示只查询一个域名下的多个关键字排名。
-->
<kall xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kw.xsd">
<kgroup>
	<kdomain>im286.com</kdomain>
	<kword>落伍者</kword>
	<kword>站长论坛</kword>
	<kword>286</kword>
	<kword>落伍者论坛</kword>
</kgroup>
<kgroup>
	<kdomain>admin5.com</kdomain>
	<kword>华文行楷</kword>
	<kword>华文新魏</kword>
	<kword>html代码</kword>
	<kword>a5论坛</kword>
</kgroup>
<kgroup>
	<kdomain>chinaz.com</kdomain>
	<kword>站长工具</kword>
	<kword>alexa</kword>
	<kword>站长之家</kword>
	<kword>网站排名</kword>
	<kword>站长</kword>
</kgroup>
<kgroup>
	<kdomain>baidu.com</kdomain>
	<kword>旭日阳刚</kword>
	<kword>小游戏</kword>
</kgroup>
<kgroup>
	<kdomain>163.com</kdomain>
	<kword>梦幻西游</kword>
	<kword>邮箱</kword>
</kgroup>
<kgroup>
	<kdomain>sina.com.cn</kdomain>
	<kword>新浪微博</kword>
	<kword>新闻</kword>
	<kword>五月天</kword>
</kgroup>
</kall>
